
#[[main]]
#  identifier = "Serviços"
#  name = "Serviços"
#  url = "showcase/services"
#  weight = 3


[[main]]
  identifier = "projects"
  name = "Projetos"
  url = "showcase/projects"
  weight = 2


[[main]]
  identifier = "posts"
  name = "Blog"
  url = "/"
  weight = 1


# [[main]]
#   parent = "posts"
#   name = "Dicas de leitura"
#   url = "tags/livros"

# [[main]]
#   parent = "posts"
#   name = "Programação"
#   url = "categories/dev"

#[[main]]
 # parent = "posts"
 # name = "DevOps"
 # url = "categories/devops"

#[[main]]
#identifier = "categories"
#name = "Categorias"
#url = "categories"
#weight = 11

[[main]]
identifier = "Tags"
name = "tags"
url = "tags"
weight = 8


#[[main]]
#  identifier = "gallery"
#  name = "Galeria"
#  url = "gallery"
#  weight = 4



#[[main]]
#  parent = "gallery"
#  name = "Temas - Vim"
#  url = "gallery/vim-themes"


[[main]]
  identifier = "archive"
  name = "Arquivo"
  url = "archive"
  weight = 6


#[[main]]
#  identifier = "notes"
#  name = "Notas"
#  url = "notes"
#  weight = 6



#[[main]]
#  identifier = "resume"
#  name = "CV"
#  url = "resume"
#  weight = 7


#[[main]]
#  identifier = "contact"
#  name = "Contato"
#  url = "contact"
#  weight = 8


[[main]]
  identifier = "about"
  name = "Sobre"
  url = "about"
  weight = 9
