baseURL = "https://alansantosmg.github.io/"
languageCode = "en-us"
defaultContentLanguage = "en"
author = "Alan Santos"
title = "Alan Santos"
theme = "hugo-vitae"
paginate = 5
enableRobotsTXT = true

#copyright = "© Copyright notice | [Vitae](https://github.com/dataCobra/hugo-vitae) theme for [Hugo](https://gohugo.io)"

pygmentsstyle = "colorful"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

googleAnalytics = "UA-148840174-2"

[taxonomies]
	tag = "tags"
	category = "categories"
	series = "series"

[params]
	# Use homepage.md instead of a list of posts
	homepage = false

	# Add meta keywords in head part (Site Keywords or Tags of Page)
	keywords = ["hugo","golang","devops","itil"]

	# Add meta description in head part
	description = "There is no place like 127.0.0.1."

	# Add pagetitle to homepage <title> tag
	pagetitle = "Alan Santos - Blog"

	# Add a subtitle to your website
	 subtitle = " "

	# Activate to show authors on pages if available
	listAuthor = false

	# Add math typesetting with KaTeX (Global with this Param)
	math = true

	# Optional 80x80 avatar image.
	avatar = "/img/avatar.jpg"

	# Optional favicons for website
	favicon = true

	# Add list of sections that should show up on the homepage
        mainSections = ["post"]

	# Add list of Sections/Types that should no be considered by RSS
	#nofeedSections = ["post"]

	# Deactivate Taxonomies for specific page types
	#disableTaxoTypes = [""]

	# Custom CSS applied to default styles. (Path could be "static/css/")
	#customCSS = "css/custom.css"

# Comments
[params.comments]
# Enable Comments with "true"
enabled = true

# Comment provider:
#   disqus (https://disqus.com)
#   commento (https://commento.io)
engine = "disqus"

# Content types to disable comments on.
disableOnTypes = ["page"]

[params.comments.disqus]
shortname = "alansantosmg-github-io" # Paste the shortname from your Disqus dashboard.

[params.comments.commento]
#host = "" # Paste the domain of you commento.io system

# Navigation
[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "T.I."
url = "/categories/Tecnologia"
weight = 2

#[[menu.main]]
#name = "Musica"
#url = "/musica"
#weight = 5

[[menu.main]]
name = "Livros"
url = "/categories/livros"

weight = 4

[[menu.main]]
name = "Projetos"
url = "/projects"
weight = 3


#[[menu.main]]
#name = "All Posts"
#url = "/post"
#weight = 6

[[menu.main]]
name = "Sobre"
url = "/about"
weight = 9

[[menu.main]]
name = "Tags"
url = "./tags"
weight = 8

[[menu.main]]
identifier = "Categorias"
name = "Categorias"
url = "/categories"
weight = 9




# Social Menu
[[params.social]]
name = "Github"
icon = "fab fa-github"
url = "https://github.com/alansantosmg"

[[params.social]]
name = "Github"
icon = "fab fa-linkedin"
url = "https://linkedin.com/in/alansantosmg"


#[[params.social]]
#name = "Email"
#icon = "fas fa-envelope"
#cmd = "mailto:alansantosmg@hotmail.com"

[[params.social]]
name = "RSS"
icon = "fas fa-rss"
url = "/index.xml"

ignoreErrors = ["error-remote-getjson"]