[en]
  title = "bhtron Dev blog"
  languageName = "en-us"
  ContentDir = "content/english"
  weight = 2

[pt]
  title = "bhtron Dev blog"
  languageName = "pt-br"
  contentDir = "content/portuguese"
  weight = 1
