
[[main]]
  identifier = "posts"
  name = "Blog"
  url = "posts"
  weight = 1


[[main]]
  identifier = "showcase"
  name = "Projetos"
  url = "showcase"
  weight = 2




[[main]]
  parent = "showcase"
  name = "Go!"
  url = "showcase/go"

[[main]]
  parent = "showcase"
  name = "Javascript"
  url = "showcase/javascript"

[[main]]
  parent = "showcase"
  name = "Python"
  url = "showcase/python"

[[main]]
  identifier = "gallery"
  name = "Galeria"
  url = "gallery"
  weight = 3



[[main]]
  parent = "gallery"
  name = "Temas - Vim"
  url = "gallery/vim-themes"

[[main]]
  identifier = "livros"
  name = "Livros"
  url = "tags/livros"
  weight = 4

[[main]]
  identifier = "archive"
  name = "Arquivo"
  url = "archive"
  weight = 5


#[[main]]
#  identifier = "notes"
#  name = "Notas"
#  url = "notes"
#  weight = 6



#[[main]]
#  identifier = "resume"
#  name = "CV"
#  url = "resume"
#  weight = 7


[[main]]
  identifier = "contact"
  name = "Contato"
  url = "contact"
  weight = 8


[[main]]
  identifier = "about"
  name = "Sobre"
  url = "about"
  weight = 9
